# 示例：从 GitHub 下载 Oh My Zsh
{{ if and (eq .chezmoi.os "linux") (contains "microsoft" .chezmoi.kernel.osrelease) }}
[".oh-my-zsh"]
  type = "git-repo"
  url  = "https://github.com/ohmyzsh/ohmyzsh.git"
  refreshPeriod = "168h"

[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
  type          = "git-repo"
  url           = "https://github.com/zsh-users/zsh-syntax-highlighting.git"
  refreshPeriod = "168h"
  [".oh-my-zsh/custom/plugins/zsh-syntax-highlighting".pull]
    args = ["--ff-only"]
    
{{ end }}

# 示例：克隆 Git 仓库
# [".vim/pack/plugins/start/vim-airline"]
#     type = "git-repo"
#     url = "https://github.com/vim-airline/vim-airline.git"
#     refreshPeriod = "168h"
