# 示例：从 GitHub 下载 Oh My Zsh
{{ if and (eq .chezmoi.os "linux") (contains "microsoft" .chezmoi.kernel.osrelease) }}
[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h" 
[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    include = ["*/*.zsh", "*/.version", "*/.revision-hash", "*/highlighters/**"]
{{ end }}

# 示例：克隆 Git 仓库
# [".vim/pack/plugins/start/vim-airline"]
#     type = "git-repo"
#     url = "https://github.com/vim-airline/vim-airline.git"
#     refreshPeriod = "168h"
